### ISSUE TITLE
Another Error 404

### ISSUE THREAD

**Issue by Tazeg** [eilgin/php-the-right-way#6]
Traductions
Espagnol => http://lamaneracorrecta.php.org.ve/ = 404

**Comment by eilgin** [comment]
Je profiterai de la #3 pour màj. la liste des traductions disponibles étant donné qu'il y a de nouvelles langues.

**Comment by eilgin** [comment]
Closes by https://github.com/eilgin/php-the-right-way/commit/786dd7e8d7ee223605e727f8c574d2d54a57dfdc
